### ISSUE TITLE
Color some cells in the team data field based on how good/bad the values are

### ISSUE THREAD

**Issue by JosiahFu** [4201VitruvianBots/ScoutingApp2023#214]
We could make a simple javascript function that generates colors for us based on inputs. For example, 0 = red, 50 = green, and fill in colors in between. Using this function, we could color the background of certain cells in the match data table (such as the avg teleop and auton points boxes from a previous issue) to easily see whether the value is good or bad. 

Data science is all about making data easy to read and understand as fast as possible - applying this as conditional formatting can make it very clear, very fast how good each team is. This would look like normal conditional formatting, similar to this: 

![Image](https://user-images.githubusercontent.com/6099416/223365101-96bdf68e-de61-44d2-a043-f003e06336f7.png)

Currently waiting for #282    -(3/26/23)

**Comment by CrisantoCarrillo** [comment]
Until the back end issue I created is completed, I will make it a temporarily hard coded range
