### ISSUE TITLE
MatchData: Lowest and Highest score of all team data

### ISSUE THREAD

**Issue by CrisantoCarrillo** [4201VitruvianBots/ScoutingApp2023#282]
To make the cell colors for the MatchData table update the colors based on the lowest and highest scores of all teams collected in the server. The cell colors in MatchData should work in a range like (0, 20) and it will make 21 shades transitioning from red to green for now. To make it better I believe we can make it so we have a range from (LowestTeamScore, HighestTeamScore), so it will transition from red to green based on all the team's performances, which requires some math done from the back end.

**Comment by JosiahFu** [comment]
Completed
