### ISSUE TITLE
MatchScouting: "Attempted balance but failed"

### ISSUE THREAD

**Issue by JosiahFu** [4201VitruvianBots/ScoutingApp2023#284]
### User Story

During the strategy meeting, we wanted to see how reliably teams could balance, but we realized often teams don't even attempt balance because other teams will balance. Having an "attempted balance but failed" in both charge station multi selects would allow us to distinguish failure from strategy and calculate a more accurate charge station reliability.

### Definition of Done

- [ ] Add "Attempted balance but failed" option to both charge station multi selects
- [ ] Modify backend to calculate balance and dock out of all the times *attempted*, i.e. when failed, balanced *or* docked

**Comment by Lauren618o** [comment]
Maybe we should teach the scouters the difference between No Points (no attempted dock) vs. Failed Balance (tried and failed to dock/balance.

**Comment by JosiahFu** [comment]
I would think it would be fairly self-explanatory but we could
