### ISSUE TITLE
MatchData: Make all the sections in the table update. (Only first search bar updates properly)

### ISSUE THREAD

**Issue by CrisantoCarrillo** [4201VitruvianBots/ScoutingApp2023#299]
So basically, I made it so the searchbars update depending on the round. It seems to work, but only the first searchbar in the table updates the data that shows up!

![Image](https://user-images.githubusercontent.com/40704658/229383343-1b13efd6-2172-4a13-a2a4-eb2be052cb4c.png)

![Image](https://user-images.githubusercontent.com/40704658/229383352-4c1ae1ef-d3db-4823-992e-7b35dd326d5a.png)

So you can see that in the first image that the first team has data, but the second one doesn't. That is odd cause both have data in the server. So i decided to go up a few matches and the second teams data showed up in the first section as well. The data will show up in the other bars if you manually search the team yourself, but we would like if it showed up automatically with the auto searchbar fill feature.

**Comment by JosiahFu** [comment]
Was this fixed on a branch?

**Comment by JosiahFu** [comment]
Seems to be fixed
