### ISSUE TITLE
Make Super Scout Interface Wireframe

### ISSUE THREAD

**Issue by kyletsubaki** [4201VitruvianBots/ScoutingApp2023#42]
- [ ] Sign in
- [ ] Match Number
- [ ] Red or Blue Alliance selection
- [ ] Static bar for alliance robots (e.g. Red 1, Red 2, Red 3)
- [ ] Robot directory is titled with text box with team number synced from the Blue Alliance
- [ ] Increment buttons for fouls and tech fouls 
- [ ] Comments box for yellow cards, red cards, defense, and disabling
- [ ] Submit Button

**Comment by blueskye04** [comment]
https://docs.google.com/presentation/d/1U2mh-lVCHVnWPrdOBY4p5g7BlHOckT5Bw8k6c_cuYQc/edit#slide=id.g1d702a07f73_0_48
